### ISSUE TITLE
Old MailChimp APIs are being sunset

### ISSUE THREAD

**Issue by kevindb** [fh-group/MailChimp-ColdFusion-API-Wrapper#7]
MailChimp [recently announced](http://devs.mailchimp.com/blog/sunsetting-previous-mailchimp-api-versions/) that they are sunsetting previous versions of their API at the end of 2016. I have put together a ColdFusion wrapper for the 3.0 API at [github.com/kevindb/cf-mailchimp](https://github.com/kevindb/cf-mailchimp/). Thank you for laying the ground work. My work is based on and heavily influenced by your wrapper for API v1.3 (attribution in the [contributors](https://github.com/kevindb/cf-mailchimp/blob/master/CONTRIBUTORS.md) file).

I just wanted to let you know that a 3.0 project has been started, since the 1.3 API will be turned off in a few months. #IAcceptPullRequests :smile:

**Comment by al3x-edge** [comment]
@kevindb Thanks so much for the mention in contributors. Glad to know people still get use out of this.  We'll actually change the README to point your repository if that is fine with you.  Would prefer to have people pointed at an up-to-date wrapper and it's fallen by the wayside for us contrary to the goals of the project.

**Comment by lxcodes** [comment]
Updated in commit: c97ecf5a6a73696875d1b205e310b38af074bb9d =]
